// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $item_item_id_ from "./routes/item/[item_id].tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $ItemView_AddToCart from "./islands/ItemView/AddToCart.tsx";
import * as $ItemView_Carousel from "./islands/ItemView/Carousel.tsx";
import * as $ItemView_Quantity from "./islands/ItemView/Quantity.tsx";
import * as $ItemView_TotalPrice from "./islands/ItemView/TotalPrice.tsx";
import * as $ItemView_UserReviewList from "./islands/ItemView/UserReviewList.tsx";
import * as $common_Navbar from "./islands/common/Navbar.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/item/[item_id].tsx": $item_item_id_,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/ItemView/AddToCart.tsx": $ItemView_AddToCart,
    "./islands/ItemView/Carousel.tsx": $ItemView_Carousel,
    "./islands/ItemView/Quantity.tsx": $ItemView_Quantity,
    "./islands/ItemView/TotalPrice.tsx": $ItemView_TotalPrice,
    "./islands/ItemView/UserReviewList.tsx": $ItemView_UserReviewList,
    "./islands/common/Navbar.tsx": $common_Navbar,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
