// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/about.tsx";
import * as $3 from "./routes/api/joke.ts";
import * as $4 from "./routes/greet/[name].tsx";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/item/[item_id].tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/ItemView/AddToCart.tsx";
import * as $$2 from "./islands/ItemView/Carousel.tsx";
import * as $$3 from "./islands/ItemView/Quantity.tsx";
import * as $$4 from "./islands/ItemView/TotalPrice.tsx";
import * as $$5 from "./islands/ItemView/UserReviewList.tsx";
import * as $$6 from "./islands/common/Navbar.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/about.tsx": $2,
    "./routes/api/joke.ts": $3,
    "./routes/greet/[name].tsx": $4,
    "./routes/index.tsx": $5,
    "./routes/item/[item_id].tsx": $6,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/ItemView/AddToCart.tsx": $$1,
    "./islands/ItemView/Carousel.tsx": $$2,
    "./islands/ItemView/Quantity.tsx": $$3,
    "./islands/ItemView/TotalPrice.tsx": $$4,
    "./islands/ItemView/UserReviewList.tsx": $$5,
    "./islands/common/Navbar.tsx": $$6,
  },
  baseUrl: import.meta.url,
};

export default manifest;
